
slurm:
  num_cores: 256
  qos: default
  walltime: 08:30:00
  partition: cpu

stochastic:
  num_samples: 35
  location1:
    distribution: uniform
    params: [5, 8]
  location2:
      distribution: uniform
      params: [8, 11]
  location3:
      distribution: uniform
      params: [11, 14]