slurm:
  num_cores: 256
  qos: default
  walltime: 02:50:00
  partition: cpu

stochastic:
  num_samples: 16
  miTumor:
    distribution: gauss
    params: [22.00, 2.00]  # mean, stddev
  k_th_tumor:
    distribution: gauss
    params: [ 8.0000E-11, 1.0000E-11]  # mean, stddev
  Sv:
    distribution: uniform
    params: [6000, 8000]
